FlashFlyers/Controllers/MyEventsController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FlashFlyers.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.AspNetCore.Identity;

namespace FlashFlyers.Controllers
{
    public class MyEventsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly StandardModel _standardDbContext;
        public MyEventsController(StandardModel standardDbContext, UserManager<ApplicationUser> userManager) {
            _standardDbContext = standardDbContext;
            _userManager = userManager;
        }
        public IActionResult Index() {
            if (User.Identity.IsAuthenticated) {
                List<int> event_ids = _standardDbContext.Users.Find(_userManager.GetUserId(User)).AuthoredEvents;
                if (event_ids == null)
                    return View(new List<EventModel>());
                List<EventModel> events = new List<EventModel>();
                for (int i = 0; i < event_ids.Count; ++i)
                    if (_standardDbContext.Find<EventModel>(event_ids[i]) != null)
                        events.Add(_standardDbContext.Find<EventModel>(event_ids[i]));
                return View(events);
            }
            else
                return View(new List<EventModel>());
        }

        public IActionResult UserEventDelete(int id) {
            ApplicationUser user = _standardDbContext.Users.Find(_userManager.GetUserId(User));
            if (_standardDbContext.Find<EventModel>(id) != null && user.AuthoredEvents.Contains(id)) {
                user.AuthoredEvents.Remove(id);
                _standardDbContext.Remove(_standardDbContext.Find<EventModel>(id));
                _standardDbContext.SaveChanges();
                return Redirect("~/MyEvents");
            }
            else
                return Error();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FlashFlyers/Views/MyEvents/Index.cshtml
@model IEnumerable<EventModel>
@{
    ViewData["Title"] = "My Events";
}
<body>
    <h2 style="position: relative; right:0;">
        My Events
    </h2>
    @{ if (!Model.Any())
                    {
        <h1>No created events!</h1> }
        @foreach (var evnt in Model.Reverse()) {
            <a href="~/@evnt.Id"> <h1>@evnt.Title</h1></a>
            if (evnt.Approved){
            <h1 style="color:forestgreen;">Approved!</h1>
            }
            else {
            <h1 style="color:darkred;">Unapproved!</h1>
            }
            <a href="~/@evnt.Id"> <embed src="@(evnt.Id)_with_qr.png" /></a>
            <p>@evnt.Description</p>
            <p>This event is happening on @evnt.Date at @evnt.Time at @evnt.Building @evnt.Room </p>
            @if (User.Identity.IsAuthenticated) {
                <a style="color:darkred;" asp-controller="MyEvents" asp-action="UserEventDelete" asp-route-id=@evnt.Id>Delete Event</a>
            }
            <p class="line" style="position: relative; right: 0;"></p>
        }
    }
</body>