FlashFlyers/Controllers/AppAdminController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FlashFlyers.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.AspNetCore.Authorization;

namespace FlashFlyers.Controllers
{
    // this controller class is meant to handle event deletion and modification
    //[Authorize(Roles ="Admin")]
    public class AppAdminController : Controller
    {
        private readonly StandardModel _standardDbContext;
        public AppAdminController(StandardModel standardDbContext) {
            _standardDbContext = standardDbContext;
        }

        public IActionResult Index() {
            return View(_standardDbContext.Events);
        }
        public IActionResult Modify() {
            return View();
        }

        public IActionResult Delete() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
        // function for removing an event by its Id
        public IActionResult DeleteEvent(int id) {
            var Event = new EventModel { Id = id };
            _standardDbContext.Remove(Event);
            _standardDbContext.SaveChanges();
            _standardDbContext.Dispose();
            return RedirectToAction("Index");
        }
        
        // function for event modification by replacing the event in the database
        // works similarly to event creation except the event Id is preserved
        // this  is in order to keep the url for the event page consistent,
        // which allows for features such as QR codes and Mapbox to function properly

        public IActionResult ApproveEvent(int id)
        {
            EventModel unapproved_event = _standardDbContext.Find<EventModel>(id);
            if (unapproved_event != null)
                unapproved_event.Approved = true;
            _standardDbContext.SaveChanges();
            _standardDbContext.Dispose();
            return RedirectToAction("Index");
        }

        public IActionResult ModifyEvent(int id, string name, string description, IFormFile flyer, string date, string time, string building, int room/*, string campus*/)
        {
            var Event = new EventModel { Id = id };
            _standardDbContext.Remove(Event);
            _standardDbContext.Update(new EventModel
            {
                Id = id,
                Title = name,
                Description = description,
                FileName = String.Concat(id.ToString(), Path.GetExtension(flyer.FileName)),
                Date = date,
                Time = time,
                Building = building,
                Room = room,
                Latitude = _standardDbContext.Find<LocationModel>(building).Latitude,
                Longitude = _standardDbContext.Find<LocationModel>(building).Longitude,
                Likes = _standardDbContext.Find<EventModel>(id).Likes
            });

            _standardDbContext.SaveChanges();
            _standardDbContext.Dispose();
            return RedirectToAction("Index");
        }
    }
}

FlashFlyers/Views/AppAdmin/Delete.cshtml
@{
    ViewData["Title"] = "Delete";
}


<h1>Delete Event By Id</h1>

<body>
    <div>
        <form method="post" enctype="multipart/form-data" asp-controller="AppAdmin" asp-action="DeleteEvent">

            <label for="Id">Event Id: </label>
            <input type="text" id="Id "name="id" maxlength="50" required />
            <br />
            <button type="submit" id="submit" value="Submit">Delete Event</button>
        </form>
    </div>
</body>

FlashFlyers/Views/AppAdmin/Index.cshtml
@model IEnumerable<EventModel>
@{
    ViewData["Title"] = "AppAdmin";
}

<h1>AppAdmin</h1>
<a asp-area="" asp-controller="AppAdmin" asp-action="Delete">Delete Event By Id</a>
<br>
<a asp-area="" asp-controller="AppAdmin" asp-action="Modify">Modify Event By Id</a>

<h2 style="position: relative; right:0;">
    Events
</h2>
@{
    // this script will generate the html for every event to the AppAdmin
    // this is in order to have a quick glance at events and the option to modify or delete by EventId

    @foreach (var evnt in Model)
    {
        DateTime eventDate = DateTime.Parse(@evnt.Date);
        DateTime currentDate = DateTime.Now;

        if (eventDate >= currentDate)
        {
            //Hard-coded base directory for now.
            <a href="~/@evnt.Id" class="h1"> @evnt.Title</a>
            <br>
            <br>
            <a href="~/@evnt.Id"> <embed src="@evnt.FileName" style="vertical-align: middle;"></a>
            <br>
            <br>
            {
                <p>Event Id: @evnt.Id</p>
                <p>Date: @evnt.Date</p>
                <p>Time: @evnt.Time</p>
                <p>Building: @evnt.Building</p>
                <p>Room: @evnt.Room</p>
                @*<p>Campus: @evnt.Campus</p>*@
                <p>Likes @evnt.Likes</p>
                <p>Description: @evnt.Description</p>
     //////////////////////////////////////////////////////////////////////////////////////////////////////////////////
     //Warning! This is not secure, use this tag for testing and demo purposes only
                <a asp-controller="AppAdmin" asp-action="DeleteEvent" asp-route-id=@evnt.Id>Delete Event</a>
                if (!evnt.Approved) {
                    <a style="color:forestgreen;" asp-controller="AppAdmin" asp-action="ApproveEvent" asp-route-id=@evnt.Id>Approve Event</a>
                    <a style="color:darkred;" asp-controller="AppAdmin" asp-action="DeleteEvent" asp-route-id=@evnt.Id>Disapprove Event</a>
                }
                <p class="line" style="position: relative; right: 0;"></p>
                <br>
            }
        }
    }
}

FlashFlyers/Views/AppAdmin/Modify.cshtml
@{
    ViewData["Title"] = "Modify";
}

<h1>Modify Event By Id</h1>

<body>
    <div>
        <form method="post" enctype="multipart/form-data" asp-controller="AppAdmin" asp-action="ModifyEvent">

            <label for="Id">Event Id: </label>
            <input type="text" id="Id " name="id" maxlength="50" required />
            <br />

            <label for="evTitle">Event Title: </label>
            <input type="text" id="name" name="name" maxlength="50" required />
            <br />

            <label for="evImg">Event Image: </label>
            <input type="file" name="flyer" class="form-control" required />
            <br />

            <label for="evDesc">Event Description: </label>
            <input type="text" id="description" name="description" maxlength="140" required />
            <br />

            <label for="evDate"> Event Date: </label>
            <input type="date" id="date" name="date" required />
            <br />

            <label for="evTime"> Event Time: </label>
            <input type="time" id="time" name="time" required />
            <br />

            <label for="locBldg">Please select a building: </label>
            <select name="building" id="building">
                <option>Mathematical Sciences</option>
                <option>Aeronautics and Engineering</option>
                <option>Liquid Crystals Materials Science</option>
                <option>Cunningham Hall</option>
                <option>Henderson Hall</option>
                <option>Smith Hall</option>
                <option>Science Research</option>
                <option>Willaims Hall</option>
                <option>Intergrated Sciences</option>
            </select>
            <br />

            <label for="locRoom">Please Specify a room number</label>
            <input type="number" id="room" name="room" />
            <br />

            @*<label for="locCamp">Please select a campus: </label>
            <select name="campus" id="campus">
                <option value="KT">Kent</option>
                <option value="GA">Geauga</option>
                <option value="AT">Ashtabula</option>
                <option value="EL">East Liverpool</option>
                <option value="SA">Salem</option>
                <option value="ST">Stark</option>
                <option value="TR">Trumbull</option>
                <option value="TU">Tuscarawas</option>
            </select>
            <br />*@

            <button type="reset" id="reset">Reset From</button>
            <button type="submit" id="submit" value="Submit">Modify Event</button>
        </form>
    </div>
</body>